# config/drone_config.yaml

drones:
  - drone_id: 0
    initial_position: [0, 0, 0]
    max_velocity: 2.0
    max_acceleration: 1.0

  - drone_id: 1
    initial_position: [2, 0, 0]
    max_velocity: 2.0
    max_acceleration: 1.0

  - drone_id: 2
    initial_position: [-2, 0, 0]
    max_velocity: 2.0
    max_acceleration: 1.0
