drones:
  - drone_id: 0
    initial_position: [0.0, 0.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 1
    initial_position: [1.0, 0.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 2
    initial_position: [2.0, 0.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 3
    initial_position: [3.0, 0.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 4
    initial_position: [4.0, 0.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 5
    initial_position: [0.0, 1.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 6
    initial_position: [1.0, 1.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 7
    initial_position: [2.0, 1.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 8
    initial_position: [3.0, 1.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0

  - drone_id: 9
    initial_position: [4.0, 1.0, 0.0]
    max_velocity: 20.0
    max_acceleration: 30.0





